# config/turn_right_config.yaml
enhanced_yolov8_detection:
  ros__parameters:
    model_name: 'turn_right_trained.pt'
    confidence_threshold: 0.15          
    iou_threshold: 0.2                  # ← MÁS ESTRICTO (elimina detecciones superpuestas)
    update_rate: 20.0                   
    enhance_image: false
    temporal_smoothing: true            
    min_detection_count: 4              # ← MÁS confirmaciones para aceptar
    image_size: 640