version: "3.8"

services:
  simulator:
    build:
      context: .
    image: puzzlebot_image:latest         # Name and tag of the created image
    container_name: puzzlebot_container   # Name assigned to the container

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ManchesterChallenge/ros2_ws/src:/root/ManchesterChallenge/ros2_ws/src  # Mounts the repository's src directory into the container

    network_mode: host                    # Uses the host's network

    environment:
      - DISPLAY=${DISPLAY}               # Passes the host DISPLAY variable to the container

    stdin_open: true                     # Keeps STDIN open (equivalent to -it)
    tty: true                            # Allocates a TTY
    privileged: true                     # Grants full hardware access (required for USB)

    devices:
      - "/dev/bus/usb:/dev/bus/usb"      # Maps the entire USB bus

    command: /bin/bash                   # Starts an interactive shell