line_follow_controller:
  ros__parameters:
    update_rate: 50.0
    linear_velocity: 0.06
    Kp_Omega: 0.2
    Ki_Omega: 0.1
    Kd_Omega: 0.1
    max_angular_speed: 1.5
    line_timeout: 0.5
    velocity_scale_factor: 1.0
    steering_deadband: 0.06

line_detection:
  ros__parameters:
    update_rate: 30.0
    target_width: 640
    target_height: 480
    perspective_tl_x: 230
    perspective_tl_y: 380
    perspective_bl_x: 230
    perspective_bl_y: 470
    perspective_tr_x: 410
    perspective_tr_y: 380
    perspective_br_x: 410
    perspective_br_y: 470
    gaussian_kernel_size: 5
    gaussian_sigma: 5
    grayscale_threshold: 170
    morph_kernel_size: 3
    morph_erode_iterations: 12
    morph_dilate_iterations: 9
    min_contour_area: 500
    max_contour_area: 5000000
    filter_alpha: 0.1

traffic_light_fsm:
  ros__parameters:
    update_rate: 50.0
    color_detection_timeout: 0.5 
    green_velocity_scale: 1.0
    yellow_velocity_scale: 0.6
    pid_toggle_service: 'line_pid/pid_toggle'
    pid_parameter_service: 'line_follow_controller/set_parameters'

color_blob_detection:
  ros__parameters:
    update_rate: 50.0
    debug_view: true

    hsv_red1_low: [0, 60, 100]
    hsv_red1_high: [10, 255, 255]
    hsv_red2_low: [160, 60, 100]
    hsv_red2_high: [180, 255, 255]
    hsv_green_low: [40, 65, 40]
    hsv_green_high: [110, 255, 255]
    hsv_yellow_low: [15, 90, 90]
    hsv_yellow_high: [40 , 255, 255]

    blob_min_threshold: 30
    blob_max_threshold: 200
    blob_min_area: 50
    blob_max_area: 10000000
    blob_min_convexity: 0.2
    blob_max_convexity: 1.0
    blob_min_circularity: 0.2
    blob_max_circularity: 1.0
    blob_min_inertia_ratio: 0.2
    blob_max_inertia_ratio: 1.0

    gaussian_kernel_size: [9, 9]
    gaussian_sigma: 2
    grayscale_threshold: 5
    morph_kernel_size: [3, 3]
    morph_erode_iterations: 4
    morph_dilate_iterations: 4

