open_loop_path_generator:
  ros__parameters:
    waypoints_json: |
      [
        {
          "x": 1.0,
          "y": 1.0,
          "total_time": 20.0
        },
        {
          "x": 2.0,
          "y": 2.0,
          "total_time": 20.0
        }
      ]
    max_linear_speed: 0.15
    max_angular_speed: 0.9
    safety_margin: 0.0